// Teste.http

### Requisição para a raiz da aplicação
GET http://localhost:5136

### Cadastrar
POST http://localhost:5136/api/sala/cadastrar
Content-Type: application/json

{
    "nome" : "Sala 5 - Privacidade", 
    "capacidade" : 1
}

### Listar
GET http://localhost:5136/api/sala/listar

### Alterar
PUT http://localhost:5136/api/sala/alterar/Sala%201%20Transparencia
Content-Type: application/json

{
    "nome" : "Sala 1 - Transparencia",
    "capacidade" : 2
}

### Remover
DELETE http://localhost:5136/api/sala/remover
Content-Type: application/json

{
    "nome" : "Sala 5 - Privacidade",
    "capacidade" : 2
}

### Buscar sala específica
GET http://localhost:5136/api/sala/buscar/Arquibancada

### Cadastrar Reserva
POST http://localhost:5136/api/reserva/cadastrar
Content-Type: application/json

{
    "NomeSala": "Sala 2 - Flexibilidade",
    "DataInicio": "2024-09-29T12:00:00",
    "DataFim": "2024-09-29T13:00:00",
    "NomePessoa": "João Silva"
}

### Listar
GET http://localhost:5136/api/reserva/listar

### Remover
DELETE http://localhost:5136/api/reserva/remover/aea9d962-61a7-45f1-86ff-b14787436c97
Content-Type: application/json

{
    "NomeSala": "Sala 1 Transparencia",
    "DataInicio": "2024-09-29T09:00:00",
    "DataFim": "2024-09-29T11:00:00",
    "NomePessoa": "João Silva"
}

### Buscar sala específica
GET http://localhost:5136/api/reserva/buscar/