# Teste.http

### Requisição para a raiz
GET http://localhost:5136

## REQUISIÇÕES DAS SALAS

### Cadastrar
POST http://localhost:5136/api/sala/cadastrar
Content-Type: application/json

{
    "nome" : "Sala de Teste 2", 
    "capacidade" : 4
}

### Listar
GET http://localhost:5136/api/sala/listar

### Alterar
PUT http://localhost:5136/api/sala/alterar/Sala%20de%20Teste
Content-Type: application/json

{
    "nome" : "Sala 1 - Transparencia",
    "capacidade" : 2
}

### Remover
DELETE http://localhost:5136/api/sala/remover
Content-Type: application/json

{
    "nome" : "Sala 1 - Transparencia"
}

### Buscar sala específica
GET http://localhost:5136/api/sala/buscar/

## REQUISIÇÕES DAS RESERVAS

### Cadastrar Reserva
POST http://localhost:5136/api/reserva/cadastrar
Content-Type: application/json

{
    "NomeSala": "Sala de Teste 2",
    "DataInicio": "2024-09-29T12:00:00",
    "DataFim": "2024-09-29T13:00:00",
    "NomePessoa": "João Silva"
}

### Listar
GET http://localhost:5136/api/reserva/listar

### Remover reserva com ID
DELETE http://localhost:5136/api/reserva/remover/

### Buscar reserva específica com ID
GET http://localhost:5136/api/reserva/buscar/